services:
  # Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: app-prod
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    command: sh -c "php-fpm"
    networks:
      - app-network-prod
    depends_on:
      db:
        condition: service_healthy

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx-prod
    restart: unless-stopped
    tty: true
    ports:
      - "8002:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network-prod
    depends_on:
      - app

  # Database Service
  db:
    image: mysql:8.0
    container_name: db-prod
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - dbdata-prod:/var/lib/mysql
    networks:
      - app-network-prod
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}"]
      timeout: 20s
      retries: 10

# Networks
networks:
  app-network-prod:
    driver: bridge

# Volumes
volumes:
  dbdata-prod:
    driver: local
